add auto pull

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -15,11 +15,57 @@ install_pkg() {
     brew install "$pkg"
   else
     echo "No supported package manager (apt-get, pacman, brew) found. Please install $pkg manually."
-    return 1
+    exit 1
   fi
 }
 
-echo "Backing up existing dotfiles..."
-cd $HOME
-yadm ls-files | grep -v "readme.md" >/tmp/yadm_files.txt
-tar -czf backup-dotfiles-$(date +%F-%H%M%S).tar.gz -T /tmp/yadm_files.txt -C $HOME
+check_command() {
+  local cmd="$1"
+  echo "Checking for command: $cmd"
+  if ! command -v "$cmd" >/dev/null 2>&1; then
+    echo "Command '$cmd' not found. Installing..."
+    install_pkg "$cmd"
+  fi
+}
+
+# end of utility functions
+# begin of module functions
+get_repo() {
+  REPOS=(
+    "http://10.0.0.152:3000/lfy/dotfiles"
+    "http://silvertech:3000/lfy/dotfiles"
+    "https://github.com/flin16/dotfiles"
+  )
+
+  for repo in "${REPOS[@]}"; do
+    echo "🔄 Trying to pull from $repo ..."
+    yadm remote set-url origin "$repo"
+
+    if yadm pull; then
+      echo "✅ Successfully pulled from $repo"
+      return 0
+    else
+      echo "❌ Failed to pull from $repo"
+      echo "Failing back to next repository in the list..."
+    fi
+  done
+
+  echo "🚨 All attempts failed. Please check your network or remote URLs."
+  exit 1
+}
+# end of module functions
+
+get_repo
+tmpdir=$(mktemp -d)
+
+if ! yadm pull; then
+  echo "yadm pull found existing files"
+  check_command tar
+  echo "Backing up existing dotfiles..."
+  cd $HOME
+  yadm_files=$tmpdir/yadm_files.txt
+  yadm ls-files | grep -v "readme.md" >$yadm_files
+  tar -czf backup-dotfiles-$(date +%F-%H%M%S).tar.gz -T $yadm_files -C $HOME
+  echo "Removing existing dotfiles..."
+
+fi
